#!/usr/bin/env bash

# Bootstrap a new Mac

set -e

# Symlink config files
# Do this first in to simplify updating this configuration.
ln gitconfig ~/.gitconfig
ln gitignore ~/.gitignore
ln editorconfig ~/.editorconfig
ln vimrc ~/.vimrc
ln -s "`pwd`/git_hooks" ~/.git_hooks

# Configure ZSH
## Install zprezto
git clone --recursive https://github.com/sorin-ionescu/prezto.git ~/.zprezto
ln zpreztorc ~/.zpreztorc
ln zshenv ~/.zshenv
ln zshrc ~/.zshrc
ln -s "`pwd`/zsh" ~/.zsh

# Install homebrew (also install xcode tools)
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew doctor

brew install git hub n

# Install VSCode and extensions
brew cask install visual-studio-code
code --install-extension vscodevim.vim

# Install homebrew cask for Mac apps
brew cask install dropbox google-chrome nvalt visual-studio-code

# Install QuickLook plugins
# details at https://github.com/sindresorhus/quick-look-plugins
brew cask install qlstephen qlmarkdown

# Create projects directory
mkdir -p ~/Projects

# Use OSX keychain for git auth
# https://help.github.com/articles/caching-your-github-password-in-git/
git config --global credential.helper osxkeychain

# Create a github access token
open "https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/"


