#!/usr/bin/env bash

# Bootstrap a new Mac
# Derived from Good Eggs developer start: https://github.com/goodeggs/developer-start

set -e

# generate an SSH key
ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa

# install homebrew (also install xcode tools)
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/HomeBrew/install/master/install)"
brew doctor
mkdir -p ~/Library/LaunchAgents

brew install git hub nodenv direnv
brew tap nodenv/nodenv
brew install nodenv-package-rehash

# install 1password from the Mac App store to get license
# brew cask install 1password

# install homebrew cask for Mac apps
brew cask install dropbox google-chrome nvalt atom slate
brew cask install 1password 1password-cli

# install QuickLook plugins
# details at https://github.com/sindresorhus/quick-look-plugins
brew cask install qlstephen qlmarkdown

# create projects directory
mkdir -p ~/Projects

# use OSX keychain for git auth
# https://help.github.com/articles/caching-your-github-password-in-git/
git config --global credential.helper osxkeychain

# Create a github access token
open "https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/"

# Install a Powerline Font
open "./fonts/Inconsolata for Powerline.otf"

# symlink config files
ln slate ~/.slate
ln gitconfig ~/.gitconfig
ln gitignore ~/.gitignore
ln editorconfig ~/.editorconfig
ln vimrc ~/.vimrc
ln zpreztorc ~/.zpreztorc
ln zshenv ~/.zshenv
ln zshrc ~/.zshrc
ln -s "`pwd`/zsh" ~/.zsh
ln -s "`pwd`/git_hooks" ~/.git_hooks
ln -s "`pwd`/atom" ~/.atom

# Clone zprezto
git clone --recursive https://github.com/sorin-ionescu/prezto.git ~/.zprezto
